// <auto-generated />
using AiDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221130719_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiDemo.Models.UserMovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserMovies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Sci-Fi",
                            Rating = 5,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Sci-Fi",
                            Rating = 5,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Sci-Fi",
                            Rating = 5,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Action",
                            Rating = 4,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Action",
                            Rating = 4,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Romance",
                            Rating = 2,
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Romance",
                            Rating = 3,
                            Title = "Titanic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
